/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-01-24T20:18:35.558Z")

@Api(value = "source", description = "the source API")
@RequestMapping(value = "/rest")
public interface SourceApi {

    @ApiOperation(value = "Link do projeto no github", nickname = "linkProjeto", notes = "Obter Link do projeto no github com o código fonte do projeto desenvolvido", response = String.class, tags={ "Código Fonte", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Link retornado com sucesso.", response = String.class) })
    @RequestMapping(value = "/source",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<String> linkProjeto();

}
